### ISSUE TITLE
how to integrate aerodrome-finance contracts in other contracts?

### ISSUE THREAD

**Issue by rugrumbledev** [aerodrome-finance/contracts#10]
I want to call aerodrome dex functions from other smart contracts. I couldn't find much useful documentation around it. Can you share any doc around how can i integrate dex in other contract from where i can just call swap method. Or if there's an offchain API that gives me calldata from swap method to be executed, that'll also work.

**Comment by stas** [comment]
Please see https://github.com/aerodrome-finance/sugar
