### ISSUE TITLE
What's the Burn Event mean? Seems it is different with Uniswap

### ISSUE THREAD

**Issue by TangMonk** [aerodrome-finance/contracts#4]
For example, this [tx](https://basescan.org/tx/0x32876fe0f2eaeb287c630690ad0432cf57e360cd100041dd797624e37226f2f0#eventlog), the man remove liquidity and `Burn Event` triggered

<img width="1113" alt="image" src="https://github.com/aerodrome-finance/contracts/assets/3498786/5dba146d-ff4f-4957-93d2-3e7fa2805f2e">

But what's the `value` and `index` mean?

In Uniswap V2 pool, Burn Event contains `amount0` and `amount1` for token1 and token2 removed amount, But I do not know what exactly is the `value` and `index` mean?

<img width="1249" alt="image" src="https://github.com/aerodrome-finance/contracts/assets/3498786/848ffca6-8c87-404b-ae17-2a456dbdccae">

I cannot found the doc about that

**Comment by stas** [comment]
Please reach out on Discord for such questions.
