### ISSUE TITLE
Getting best route to swap tokens

### ISSUE THREAD

**Issue by nmalzieu** [aerodrome-finance/contracts#5]
Hi there! I see that you don't have an API to get a quote / best route to swap 2 tokens.
By looking at github, I saw that Velodrome used to have one (https://api.velodrome.finance/api/v1/routeAssets) but it seems it's not online anymore.
What is the current way to get the best route to swap 2 tokens (specifically on Aerodrome but if you have documentation on Velodrome and it's close I'm ok with that) .
Thanks a lot!

**Comment by stas** [comment]
There's no API. Please reach out on Discord for such questions.
