### ISSUE TITLE
CL100-WETH/USDC Contract not showing in my Dashboard

### ISSUE THREAD

**Issue by ngisvold** [aerodrome-finance/contracts#6]
Here is my contract: 0xc741beb2156827704A1466575ccA1cBf726a1178

It no longer shows in my dashboard after withdrawing emissions.

**Comment by ngisvold** [comment]
I actually have two contracts not showing: https://basescan.org/token/0xc741beb2156827704a1466575cca1cbf726a1178?a=0xa578994a409696e4d8d1cdcc93aba4c34022c93b

**Comment by stas** [comment]
Please reach out on Discord for such questions.
