### ISSUE TITLE
UX: Unsafe swaps - Poor visibility and difficult to disable

### ISSUE THREAD

**Issue by KaladinB4** [aerodrome-finance/contracts#9]
# UX: Unsafe swaps - Poor visibility and difficult to disable

## Problem Description

The Aerodrome Finance web app has critical UX issues with unsafe swaps:

- Unsafe swap status lacks clear indication after enabling.
- High slippage and price impact warnings are not visually emphasized.
- Disabling unsafe swaps is unnecessarily difficult compared to enabling them.
- Persistent unsafe swap settings between sessions are not visually highlighted/warned about.
- 

## Current Behavior

After enabling unsafe swaps for memecoins, subsequent trades show:

```
Swap
1. Exchange rate found...
Refresh
2. 0.5% slippage applied... Adjust
3. Minimum received 6.55 USDC
4. 45.63% price impact is unsafe
5. Allowance not granted for MOCHI
Allow MOCHI
6. Waiting for pending actions...
```

Note: The 45.63% price impact warning lacks visual emphasis.

![Screenshot from 2024-08-10 13-39-17](https://github.com/user-attachments/assets/7f14b7d2-21e4-4750-b2a7-f480202be2d9)

## Expected Behavior

- Clear, persistent indicator for enabled unsafe swaps.
- Visually distinct warnings for high slippage/price impact.
- Easily accessible, prominent toggle to enable/disable unsafe swaps.
- Additional risk warnings (e.g., MEV).

## Potential Impact

Users may unknowingly make high-risk trades, potentially leading to significant financial losses. I had forgot about this memecoin/enabling unsafe swaps weeks ago, it was quite easy to enable it, but now I am struggling to visually locate a way to DISABLE these unsafe swaps.

## Suggested Improvements

1. Add a visible "Unsafe Swaps Enabled" indicator.
2. Implement color-coding for risk levels.
3. Create an easily accessible toggle for unsafe swaps.
4. Add informational tooltips explaining risks.
5. Require confirmation for high-risk trades.

Improving these safety features would enhance user trust and platform safety and save some users money.
![Screenshot from 2024-08-10 13-39-17](https://github.com/user-attachments/assets/762fcff8-e6bc-4ebc-99c0-743d9ffa36b1)

## Environment

- Web application
- Frontend issue

**Comment by KaladinB4** [comment]
Here's a visual representation of the suggested UI improvements:

```
+-----------------------------------------------------+
|                      Swap                           |
| Exchange rate found...                     Refresh  |
|                                                     |
| 1 MOCHI                                             |
| 0.00001 USDC                                        |
|                                                     |
| 0.5% slippage applied...                    Adjust  |
|                                                     |
| Minimum received 6.55 USDC                          |
|                                                     |
| +---------------------------------------------------+
| |                   !!! WARNING !!!                 |
| |        45.63% PRICE IMPACT IS UNSAFE              |
| |          UNSAFE SWAPS ARE ENABLED                 |
| +---------------------------------------------------+
|                                                     |
| Allowance not granted for MOCHI              Allow  |
|                                                     |
| Waiting for pending actions...                      |
|                                                     |
| +---------------------------------------------------+
| |          [  DISABLE UNSAFE SWAPS  ]               |
| +---------------------------------------------------+
+-----------------------------------------------------+
```

Key improvements:

1. **Prominent Warning**: The high slippage/price impact warning is now enclosed in a box with multiple exclamation marks, making it much more noticeable than the "1 MOCHI" information.

2. **Unsafe Swaps Toggle**: A new button to disable unsafe swaps is added at the bottom of the interface, making it easy for users to turn off this risky feature.

3. **Visual Hierarchy**: The warning about price impact and unsafe swaps is given the highest visual priority in the interface.

In an actual implementation, the warning box could use bright colors (e.g., red background with white text) to further emphasize the risk. The "DISABLE UNSAFE SWAPS" button could be styled prominently, perhaps with a yellow background to indicate caution.

These changes would significantly improve the visibility of critical information and make it easier for users to manage their risk exposure.

**Comment by stas** [comment]
Appreciate the feedback. There's a bunch of updates that were made for this screen. For future reference please use the Discord for such feedback, this repository is reserved for smart contract purposes.

**Comment by amilkov3** [comment]
with respect, this is a dangerously poor UX. why is there not a $ in/out figure displayed like every other UX? i lost 4k$+ on a single swap because this is the only indication the UI gives you before you approve. And I doubt im the first
![image](https://github.com/user-attachments/assets/00c71c57-63bb-4a14-a2b7-dcf735b38a9a)

**Comment by stas** [comment]
@amilkov3 I think I got your message. Please stop now. I've already asked you to keep things on-topic.

This thread is now locked.
